export * from './borrowerController.service';
import { BorrowerControllerService } from './borrowerController.service';
export * from './commonController.service';
import { CommonControllerService } from './commonController.service';
export * from './disburseController.service';
import { DisburseControllerService } from './disburseController.service';
export * from './loanApplicationController.service';
import { LoanApplicationControllerService } from './loanApplicationController.service';
export * from './loginController.service';
import { LoginControllerService } from './loginController.service';
export * from './webhookController.service';
import { WebhookControllerService } from './webhookController.service';
export const APIS = [BorrowerControllerService, CommonControllerService, DisburseControllerService, LoanApplicationControllerService, LoginControllerService, WebhookControllerService];
