---
openapi: 3.0.3
info:
  title: bnpl-service API
  version: 1.0-SNAPSHOT
paths:
  /v1/admin/merchants:
    get:
      tags:
      - Admin Controller
      parameters:
      - name: bdStaff
        in: query
        schema:
          type: string
      - name: code
        in: query
        schema:
          type: string
      - name: email
        in: query
        schema:
          type: string
      - name: id
        in: query
        schema:
          type: string
      - name: mobile
        in: query
        schema:
          type: string
      - name: name
        in: query
        schema:
          type: string
      - name: productType
        in: query
        schema:
          type: string
      - name: status
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseListMerchant'
    put:
      tags:
      - Admin Controller
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMerchantRequestDto'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseMerchant'
    post:
      tags:
      - Admin Controller
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMerchantRequestDto'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseMerchant'
    delete:
      tags:
      - Admin Controller
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteMerchantRequestDto'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseString'
  /v1/admin/merchants/qrcode:
    post:
      tags:
      - Admin Controller
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateMerchantQrRequestDto'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseString'
  /v1/admin/merchants/{id}:
    get:
      tags:
      - Bnpl Controller
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseMerchant'
  /v1/merchants/{id}:
    get:
      tags:
      - Merchant Controller
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseMerchant'
components:
  schemas:
    ApiResponseListMerchant:
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/Merchant'
        errorCode:
          type: string
        message:
          type: string
        responseCode:
          format: int32
          type: integer
    ApiResponseMerchant:
      type: object
      properties:
        result:
          $ref: '#/components/schemas/Merchant'
        errorCode:
          type: string
        message:
          type: string
        responseCode:
          format: int32
          type: integer
    ApiResponseString:
      type: object
      properties:
        result:
          type: string
        errorCode:
          type: string
        message:
          type: string
        responseCode:
          format: int32
          type: integer
    CreateMerchantRequestDto:
      required:
      - code
      - name
      - mobile
      - email
      - identificationNumber
      - establishTime
      - status
      type: object
      properties:
        code:
          pattern: \S
          type: string
          nullable: false
        name:
          pattern: \S
          type: string
          nullable: false
        address:
          type: string
        ward:
          type: string
        district:
          type: string
        province:
          type: string
        bdStaffId:
          type: string
        sellType:
          type: string
        mobile:
          pattern: \S
          type: string
          nullable: false
        email:
          pattern: \S
          type: string
          nullable: false
        website:
          type: string
        identificationNumber:
          pattern: \S
          type: string
          nullable: false
        establishTime:
          pattern: \S
          type: string
          nullable: false
        productType:
          type: string
        serviceFee:
          format: double
          type: number
        status:
          pattern: \S
          type: string
          nullable: false
        icon:
          type: string
        description:
          type: string
    DeleteMerchantRequestDto:
      required:
      - ids
      type: object
      properties:
        ids:
          type: array
          items:
            type: string
          nullable: false
    GenerateMerchantQrRequestDto:
      required:
      - id
      type: object
      properties:
        id:
          pattern: \S
          type: string
          nullable: false
    Merchant:
      type: object
      properties:
        id:
          type: string
        code:
          type: string
        name:
          type: string
        address:
          type: string
        ward:
          type: string
        district:
          type: string
        province:
          type: string
        bdStaffId:
          type: string
        sellType:
          type: string
        mobile:
          type: string
        email:
          type: string
        website:
          type: string
        identificationNumber:
          type: string
        establishTime:
          type: string
        productType:
          type: string
        serviceFee:
          format: double
          type: number
        status:
          type: string
        icon:
          type: string
        description:
          type: string
        createdAt:
          type: string
        createdBy:
          type: string
        updatedAt:
          type: string
        updatedBy:
          type: string
    UpdateMerchantRequestDto:
      required:
      - id
      type: object
      properties:
        id:
          pattern: \S
          type: string
          nullable: false
        code:
          type: string
        name:
          type: string
        address:
          type: string
        ward:
          type: string
        district:
          type: string
        province:
          type: string
        bdStaffId:
          type: string
        sellType:
          type: string
        mobile:
          type: string
        email:
          type: string
        website:
          type: string
        identificationNumber:
          type: string
        establishTime:
          type: string
        productType:
          type: string
        serviceFee:
          format: double
          type: number
        status:
          type: string
        icon:
          type: string
        description:
          type: string
