---
openapi: 3.0.0
paths:
  "/v1/cde/questions/{id}":
    get:
      operationId: CdeController_getPdQuestionById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiResponse"
      tags:
        - cde
    put:
      operationId: CdeController_updatePdQuestion
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdatePdQuestionRequestDto"
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiResponse"
      tags:
        - cde
    delete:
      operationId: CdeController_deletePdQuestion
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/DeletePdQuestionRequestDto"
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiResponse"
      tags:
        - cde
  "/v1/cde/questions":
    get:
      operationId: CdeController_getPdQuestion
      parameters:
        - name: id
          required: false
          in: query
          schema:
            type: number
        - name: code
          required: false
          in: query
          schema:
            type: string
        - name: content
          required: false
          in: query
          schema:
            type: string
        - name: description
          required: false
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiResponse"
      tags:
        - cde
    post:
      operationId: CdeController_createPdQuestion
      parameters: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreatePdQuestionRequestDto"
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiResponse"
      tags:
        - cde
  "/v1/cde/groups/{id}":
    get:
      operationId: CdeController_getPdGroupById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiResponse"
      tags:
        - cde
    put:
      operationId: CdeController_updatePdGroup
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdatePdGroupRequestDto"
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiResponse"
      tags:
        - cde
    delete:
      operationId: CdeController_deletePdGroup
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/DeletePdQuestionRequestDto"
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiResponse"
      tags:
        - cde
  "/v1/cde/groups":
    get:
      operationId: CdeController_getPdGroup
      parameters:
        - name: id
          required: false
          in: query
          schema:
            type: number
        - name: code
          required: false
          in: query
          schema:
            type: string
        - name: content
          required: false
          in: query
          schema:
            type: string
        - name: description
          required: false
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiResponse"
      tags:
        - cde
    post:
      operationId: CdeController_createPdGroup
      parameters: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreatePdGroupRequestDto"
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiResponse"
      tags:
        - cde
  "/v1/cde/models/{id}":
    get:
      operationId: CdeController_getPdModelById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiResponse"
      tags:
        - cde
    put:
      operationId: CdeController_updatePdModel
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdatePdModelRequestDto"
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiResponse"
      tags:
        - cde
    delete:
      operationId: CdeController_deletePdModel
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/DeletePdModelRequestDto"
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiResponse"
      tags:
        - cde
  "/v1/cde/models":
    get:
      operationId: CdeController_getPdModel
      parameters:
        - name: id
          required: false
          in: query
          schema:
            type: number
        - name: code
          required: false
          in: query
          schema:
            type: string
        - name: content
          required: false
          in: query
          schema:
            type: string
        - name: description
          required: false
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiResponse"
      tags:
        - cde
    post:
      operationId: CdeController_createPdModel
      parameters: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreatePdModelRequestDto"
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiResponse"
      tags:
        - cde
  "/v1/loan-products":
    get:
      operationId: LoanProductController_getLoanProduct
      parameters: [ ]
      responses:
        '200':
          description: ''
      tags:
        - loan-products
    post:
      operationId: LoanProductController_createLoanProduct
      parameters: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateLoanProductDto"
      responses:
        '201':
          description: ''
      tags:
        - loan-products
info:
  title: MonexcoreService
  description: ''
  version: 1.0.0
  contact: { }
tags: [ ]
servers: [ ]
components:
  schemas:
    ApiResponse:
      type: object
      properties:
        result:
          type: object
        errorCode:
          type: string
        message:
          type: object
        responseCode:
          type: number
      required:
        - result
        - errorCode
        - message
        - responseCode
    CreatePdQuestionRequestDto:
      type: object
      properties:
        createdAt:
          type: string
        createdBy:
          type: string
        updatedAt:
          type: string
        updatedBy:
          type: string
        code:
          type: string
        content:
          type: string
        description:
          type: string
        groupIds:
          type: array
          items:
            type: number
        answerType:
          type: string
        placeHolder:
          type: string
        answers:
          type: array
          items:
            type: string
      required:
        - code
        - content
        - answerType
    UpdatePdQuestionRequestDto:
      type: object
      properties:
        createdAt:
          type: string
        createdBy:
          type: string
        updatedAt:
          type: string
        updatedBy:
          type: string
        code:
          type: string
        content:
          type: string
        description:
          type: string
        answerType:
          type: string
        groupIds:
          type: array
          items:
            type: number
        answers:
          type: array
          items:
            type: string
        placeHolder:
          type: string
    DeletePdQuestionRequestDto:
      type: object
      properties:
        createdAt:
          type: string
        createdBy:
          type: string
        updatedAt:
          type: string
        updatedBy:
          type: string
    CreatePdGroupRequestDto:
      type: object
      properties:
        createdAt:
          type: string
        createdBy:
          type: string
        updatedAt:
          type: string
        updatedBy:
          type: string
        code:
          type: string
        content:
          type: string
        description:
          type: string
        modelId:
          type: number
        questionIds:
          type: array
          items:
            type: number
        status:
          type: number
      required:
        - code
        - content
        - status
    UpdatePdGroupRequestDto:
      type: object
      properties:
        createdAt:
          type: string
        createdBy:
          type: string
        updatedAt:
          type: string
        updatedBy:
          type: string
        code:
          type: string
        content:
          type: string
        description:
          type: string
        questionIds:
          type: array
          items:
            type: number
        modelId:
          type: number
        status:
          type: number
    CreatePdModelRequestDto:
      type: object
      properties:
        createdAt:
          type: string
        createdBy:
          type: string
        updatedAt:
          type: string
        updatedBy:
          type: string
        code:
          type: string
        content:
          type: string
        description:
          type: string
        loanProductId:
          type: number
        groupIds:
          type: array
          items:
            type: number
        status:
          type: number
      required:
        - code
        - content
        - status
    UpdatePdModelRequestDto:
      type: object
      properties:
        createdAt:
          type: string
        createdBy:
          type: string
        updatedAt:
          type: string
        updatedBy:
          type: string
        code:
          type: string
        content:
          type: string
        description:
          type: string
        loanProductId:
          type: number
        groupIds:
          type: array
          items:
            type: number
        status:
          type: number
    DeletePdModelRequestDto:
      type: object
      properties:
        createdAt:
          type: string
        createdBy:
          type: string
        updatedAt:
          type: string
        updatedBy:
          type: string
    CreateLoanProductDto:
      type: object
      properties:
        createdAt:
          type: string
        createdBy:
          type: string
        updatedAt:
          type: string
        updatedBy:
          type: string
        code:
          type: string
        name:
          type: string
      required:
        - code
        - name
