export enum MODAL_TYPE {
  LOGIN = "login-register",
  FORGOT_PASSWORD = "forgot-password",
  FORGOT_PASSWORD_OTP = "forgot-password-otp",
  SIGNUP_OTP = "signup-otp",
  PL_SUCCESS = "payday-loan-success",
  PL_ERROR = "payday-loan-error",
  PL_WAITING = "payday-loan-waiting",
  PL_FAILED = "payday-loan-failed",
  PL_NOT_EMPLOYEE = "payday-loan-not-employee",
  PL_CHOOSE_VOUCHER = "payday-loan-choose-voucher",
  PL_TYPE_OTP = "payday-loan-type-otp",
  PL_ELECTRONIC_SINGING = "payday-loan-electronic-signing",
  PL_ADS = "payday-loan-ads",
  PL_GUIDE_SIGN_CONTRACT = "payday-loan-guide-sign-contract",
  PL_GUIDE_SIGN_LETTER_TERM_OF_SERVICE = "payday-loan-guide-sign-letter-term-of-service",
  PL_COLLATERAL_DOCUMENT_EXAMPLE = "payday-loan-collateral-document-example",
  PL_SALARY_DOCUMENT_EXAMPLE = "payday-loan-salary-document-example",
  PL_CONFIRM_FINALIZATION = "payday-loan-confirm-finalization"
}
