export enum NAV_ITEM {
  DASHBOARD = 'DASHBOARD',
  LOANAPP = 'LOANAPP',
  CUSTOMER = 'CUSTOMER',
  INSURANCE = 'INSURANCE',
  SAVING = 'SAVING',
}

export enum DOCUMENT_BTN_TYPE {
  UPLOAD = 'UPLOAD',
  UPDATE = 'UPDATE',
  DOWNLOAD = 'DOWNLOAD',
  DELETE = 'DELETE',
}
