export enum NAV_ITEM {
  DASHBOARD = 'DASHBOARD',
  LOANAPP = 'LOANAPP',
  CUSTOMER = 'CUSTOMER',
  INSURANCE = 'INSURANCE',
  SAVING = 'SAVING',
}

export enum DOCUMENT_BTN_TYPE {
  UPLOAD = 'UPLOAD',
  UPDATE = 'UPDATE',
  DOWNLOAD = 'DOWNLOAD',
  DELETE = 'DELETE',
}

export enum QUERY_CONDITION_TYPE {
  GREATER_THAN = '__gt',
  GREATER_THAN_OR_EQUAL = '__ge',
  LESS_THAN = '__lt',
  LESS_THAN_OR_EQUAL = '__le',
  BETWEEN = '__bw',
  START_WITH = '__sw',
  END_WITH = '__ew',
  NOT_EQUAL = '__ne',
  EQUAL = '__e',
  IN = '__in',
  LIKE = '__~',
}

export enum DATA_CELL_TYPE {
  TEXT = 'TEXT',
  DATETIME = 'DATETIME',
  STATUS = 'STATUS',
  CURRENCY = 'CURRENCY',
}

export enum DATA_STATUS_TYPE {
  PL_UI_STATUS = 'PL_UI_STATUS',
  PL_HMG_STATUS = 'PL_HMG_STATUS',
  PL_TNG_STATUS = 'PL_TNG_STATUS',
  PL_OTHER_STATUS = 'PL_OTHER_STATUS',
  PL_REPAYMENT_STATUS = 'PL_REPAYMENT_STATUS',
}

export enum FILTER_TYPE {
  SELECT = 'SELECT',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  DATETIME = 'DATETIME',
}

export enum FILTER_ACTION_TYPE {
  ITEM_ACTION = 'ITEM_ACTION',
  FILTER_EXTRA_ACTION = 'FILTER_EXTRA_ACTION',
  SUB_ITEM_ACTION = 'SUB_ITEM_ACTION',
}

export enum FILTER_DATETIME_TYPE {
  TIME_FRAME = 'TIME_FRAME',
  TIME_RANGE = 'TIME_RANGE',
}

export enum RESPONSE_CODE {
  SUCCESS = 200,
  ERROR = 400,
}
