export enum PAYDAY_LOAN_STATUS {
  NOT_VERIFY_YET = "NOT_VERIFY_YET",
  FUNDED = "FUNDED",
  DOCUMENT_AWAITING = "DOCUMENT_AWAITING",
  INITIALIZED = "INITIALIZED",
  AWAITING_APPROVAL = "AWAITING_APPROVAL",
  DOCUMENTATION_COMPLETE = "DOCUMENTATION_COMPLETE",
  REJECTED = "REJECTED",
  WITHDRAW = "WITHDRAW",
  AUCTION = "AUCTION",
  CONTRACT_ACCEPTED = "CONTRACT_ACCEPTED",
  AWAITING_DISBURSEMENT = "AWAITING_DISBURSEMENT",
  DISBURSED = "DISBURSED",
  IN_REPAYMENT = "IN_REPAYMENT",
  COMPLETED = "COMPLETED",
  OVERDUE_L2 = "OVERDUE_L2",
  CONTRACT_REJECTED = "CONTRACT_REJECTED",
  UNKNOWN_STATUS = "UNKNOWN_STATUS",
  CALLBACK_PAYMENT_RESULT = "CALLBACK_PAYMENT_RESULT"
}

export enum PAYDAY_LOAN_UI_STATUS {
  NOT_COMPLETE_EKYC_YET = "NOT_COMPLETE_EKYC_YET",
  NOT_COMPLETE_FILL_EKYC_YET = "NOT_COMPLETE_FILL_EKYC_YET",
  NOT_ACCEPTING_TERM_YET = "NOT_ACCEPTING_TERM_YET",
  NOT_COMPLETE_CDE_YET = "NOT_COMPLETE_CDE_YET",
  COMPLETED_CDE = "COMPLETED_CDE"
}

export enum PAYDAY_LOAN_STATUS_PAGE {
  NOT_COMPLETE_EKYC_YET = "PlEKYC",
  NOT_COMPLETE_FILL_EKYC_YET = "PlConfirmInformation",
  NOT_ACCEPTING_TERM_YET = "PlContractTermsOfService",
  NOT_COMPLETE_CDE_YET = "PlAdditionalInformation",
  COMPLETED_CDE = "PlChooseAmountToBorrow"
}

export enum PAYDAY_LOAN_STEP {
  ELECTRONIC_IDENTIFIERS = 1,
  CONFIRM_INFORMATION = 2,
  ADDITIONAL_INFORMATION = 3,
  CHOOSE_AMOUNT_TO_BORROW = 4,
  CONTRACT_SIGNING = 5
}

export enum PAYDAY_LOAN_UI_STATUS_ORDER_NUMBER {
  NOT_COMPLETE_EKYC_YET = 1,
  NOT_COMPLETE_FILL_EKYC_YET = 2,
  NOT_ACCEPTING_TERM_YET = 3,
  NOT_COMPLETE_CDE_YET = 4,
  COMPLETED_CDE = 5
}

export enum DOCUMENT_TYPE {
  ID_CARD = "ID_CARD",
  FRONT_ID_CARD = "FRONT_ID_CARD",
  BACK_ID_CARD = "BACK_ID_CARD",
  SELFIE = "SELFIE",
  BANK_BOOK = "BANK_BOOK",
  PAY_SLIP = "PAY_SLIP",
  UN_KNOWN = "UN_KNOWN",
  CONTRACT = "CONTRACT",
  LETTER_OF_ACCEPTANCE = "LETTER_OF_ACCEPTANCE",
  VEHICLE_REGISTRATION = "VEHICLE_REGISTRATION",
  SALARY_INFORMATION_ONE = "SALARY_INFORMATION_ONE",
  SALARY_INFORMATION_TWO = "SALARY_INFORMATION_TWO",
  SALARY_INFORMATION_THREE = "SALARY_INFORMATION_THREE"
}

export enum ERROR_CODE {
  ACCOUNT_EXISTED = "ACCOUNT_EXISTED",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  ACCOUNT_NOT_EXIST = "ACCOUNT_NOT_EXIST",
  MISS_PARAM = "MISS_PARAM",
  DATA_ERROR = "DATA_ERROR",
  WRONG_PASSWORD = "WRONG_PASSWORD",
  OTP_EXPIRE_TIME = "OTP_EXPIRE_TIME",
  OTP_INVALID = "OTP_INVALID",
  OTP_CONFIRM_MAXIMUM = "OTP_CONFIRM_MAXIMUM",
  SESSION_SIGN_ALREADY_EXIST = "SESSION_SIGN_ALREADY_EXIST",
  LOCK_CREATE_NEW_SESSION = "LOCK_CREATE_NEW_SESSION",
  DO_NOT_EXIST_VIRTUAL_ACCOUNT = "DO_NOT_EXIST_VIRTUAL_ACCOUNT",
  NOT_CURRENT_LOAN_REPAYMENT_ERROR = "NOT_CURRENT_LOAN_REPAYMENT_ERROR"
}

export enum SIGN_STATUS {
  ACCEPTED = "ACCEPTED",
  AWAITING_BORROWER_SIGNATURE = "AWAITING_BORROWER_SIGNATURE",
  AWAITING_EPAY_SIGNATURE = "AWAITING_EPAY_SIGNATURE",
  DONE = "DONE"
}

export enum GPAY_RESULT_STATUS {
  ORDER_PENDING = "ORDER_PENDING",
  ORDER_PROCESSING = "ORDER_PROCESSING",
  ORDER_SUCCESS = "ORDER_SUCCESS",
  ORDER_FAILED = "ORDER_FAILED",
  ORDER_CANCEL = "ORDER_CANCEL",
  ORDER_VERIFYING = "ORDER_VERIFYING"
}

export enum REPAYMENT_STATUS {
  OVERDUE = "OVERDUE"
}
