/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SigningPosition } from './signingPosition';


export interface DocumentSigningLocationEntity { 
    id?: string;
    companyName?: DocumentSigningLocationEntity.CompanyNameEnum;
    documentType?: string;
    page?: number;
    positionBorrower?: SigningPosition;
    positionInvestor?: SigningPosition;
    positionEpay?: SigningPosition;
}
export namespace DocumentSigningLocationEntity {
    export type CompanyNameEnum = 'HMG' | 'TNG';
    export const CompanyNameEnum = {
        Hmg: 'HMG' as CompanyNameEnum,
        Tng: 'TNG' as CompanyNameEnum
    };
}


