/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SendSampleNotificationRequest { 
    customerId: string;
    date: string;
    fcmToken: string;
    notiBody: string;
    notiTitle: string;
    notiType: string;
}

