/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateTemplateStatusRequest { 
    nameTemplate: string;
    type: UpdateTemplateStatusRequest.TypeEnum;
}
export namespace UpdateTemplateStatusRequest {
    export type TypeEnum = 'EMAIL' | 'SMS' | 'NOTIFICATION';
    export const TypeEnum = {
        Email: 'EMAIL' as TypeEnum,
        Sms: 'SMS' as TypeEnum,
        Notification: 'NOTIFICATION' as TypeEnum
    };
}


