export * from './apiResourceController.service';
import { ApiResourceControllerService } from './apiResourceController.service';
export * from './applicationController.service';
import { ApplicationControllerService } from './applicationController.service';
export * from './applicationHmgController.service';
import { ApplicationHmgControllerService } from './applicationHmgController.service';
export * from './approvalLetterController.service';
import { ApprovalLetterControllerService } from './approvalLetterController.service';
export * from './bankController.service';
import { BankControllerService } from './bankController.service';
export * from './companyController.service';
import { CompanyControllerService } from './companyController.service';
export * from './customerController.service';
import { CustomerControllerService } from './customerController.service';
export * from './openApiControllerWebMvc.service';
import { OpenApiControllerWebMvcService } from './openApiControllerWebMvc.service';
export * from './swagger2ControllerWebMvc.service';
import { Swagger2ControllerWebMvcService } from './swagger2ControllerWebMvc.service';
export const APIS = [ApiResourceControllerService, ApplicationControllerService, ApplicationHmgControllerService, ApprovalLetterControllerService, BankControllerService, CompanyControllerService, CustomerControllerService, OpenApiControllerWebMvcService, Swagger2ControllerWebMvcService];
