export * from './apiController.service';
import { ApiControllerService } from './apiController.service';
export * from './apiResourceController.service';
import { ApiResourceControllerService } from './apiResourceController.service';
export * from './applicationHmgController.service';
import { ApplicationHmgControllerService } from './applicationHmgController.service';
export * from './applicationTngController.service';
import { ApplicationTngControllerService } from './applicationTngController.service';
export * from './approvalLetterController.service';
import { ApprovalLetterControllerService } from './approvalLetterController.service';
export * from './bankController.service';
import { BankControllerService } from './bankController.service';
export * from './cityController.service';
import { CityControllerService } from './cityController.service';
export * from './communeController.service';
import { CommuneControllerService } from './communeController.service';
export * from './companyController.service';
import { CompanyControllerService } from './companyController.service';
export * from './customerController.service';
import { CustomerControllerService } from './customerController.service';
export * from './districtController.service';
import { DistrictControllerService } from './districtController.service';
export * from './ekycController.service';
import { EkycControllerService } from './ekycController.service';
export * from './insuranceController.service';
import { InsuranceControllerService } from './insuranceController.service';
export * from './openApiControllerWebMvc.service';
import { OpenApiControllerWebMvcService } from './openApiControllerWebMvc.service';
export * from './paymentController.service';
import { PaymentControllerService } from './paymentController.service';
export * from './ratingController.service';
import { RatingControllerService } from './ratingController.service';
export * from './swagger2ControllerWebMvc.service';
import { Swagger2ControllerWebMvcService } from './swagger2ControllerWebMvc.service';
export * from './tngDataTransactionController.service';
import { TngDataTransactionControllerService } from './tngDataTransactionController.service';
export const APIS = [ApiControllerService, ApiResourceControllerService, ApplicationHmgControllerService, ApplicationTngControllerService, ApprovalLetterControllerService, BankControllerService, CityControllerService, CommuneControllerService, CompanyControllerService, CustomerControllerService, DistrictControllerService, EkycControllerService, InsuranceControllerService, OpenApiControllerWebMvcService, PaymentControllerService, RatingControllerService, Swagger2ControllerWebMvcService, TngDataTransactionControllerService];
