/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Response { 
    account_number?: string;
    account_name?: string;
    status?: string;
    start_at?: string;
    expire_at?: string;
    balance?: number;
    account_type?: string;
    number_of_transfer?: number;
    max_amount?: number;
    min_amount?: number;
    equal_amount?: number;
    signature?: string;
}

