/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceiverInfoDTO } from './receiverInfoDTO';
import { AssetInfoDTO } from './assetInfoDTO';


export interface InsuranceOrder { 
    id?: string;
    customerId?: string;
    typeId?: string;
    packageId?: string;
    code?: string;
    status?: string;
    duration?: string;
    price?: number;
    assetInfo?: AssetInfoDTO;
    receiverInfo?: ReceiverInfoDTO;
    contractPath?: string;
    createdAt?: string;
}

