/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SearchPaydayLoanResult { 
    customerId?: string;
    loanId?: string;
    loanCode?: string;
    tenure?: number;
    status?: string;
    repaymentStatus?: string;
    amount?: number;
    createdAt?: string;
    customerName?: string;
    mobileNumber?: string;
    emailAddress?: string;
}

