export * from './approvalLetterController.service';
import { ApprovalLetterControllerService } from './approvalLetterController.service';
export * from './companyController.service';
import { CompanyControllerService } from './companyController.service';
export * from './infoController.service';
import { InfoControllerService } from './infoController.service';
export * from './infoV2Controller.service';
import { InfoV2ControllerService } from './infoV2Controller.service';
export * from './kalapaController.service';
import { KalapaControllerService } from './kalapaController.service';
export * from './kalapaV2Controller.service';
import { KalapaV2ControllerService } from './kalapaV2Controller.service';
export * from './newsletterController.service';
import { NewsletterControllerService } from './newsletterController.service';
export * from './notificationController.service';
import { NotificationControllerService } from './notificationController.service';
export * from './ratingController.service';
import { RatingControllerService } from './ratingController.service';
export * from './tngController.service';
import { TngControllerService } from './tngController.service';
export const APIS = [ApprovalLetterControllerService, CompanyControllerService, InfoControllerService, InfoV2ControllerService, KalapaControllerService, KalapaV2ControllerService, NewsletterControllerService, NotificationControllerService, RatingControllerService, TngControllerService];
