/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateRatingRequest { 
    customerId: string;
    applicationId: string;
    applicationType?: CreateRatingRequest.ApplicationTypeEnum;
}
export namespace CreateRatingRequest {
    export type ApplicationTypeEnum = 'PDL_TNG' | 'PDL_HMG' | 'INSURANCE';
    export const ApplicationTypeEnum = {
        PdlTng: 'PDL_TNG' as ApplicationTypeEnum,
        PdlHmg: 'PDL_HMG' as ApplicationTypeEnum,
        Insurance: 'INSURANCE' as ApplicationTypeEnum
    };
}


