/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BorrowerStepOneInput { 
    customerId: string;
    password: string;
    confirmPassword: string;
    mobileNumber: string;
    firstName: string;
    dateOfBirth: string;
    gender: string;
    identityNumberOne: string;
    identityNumberSix?: string;
    addressOneLine1?: string;
    addressTwoLine1?: string;
}

