/**
 * contract-service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateDocumentResponse } from './createDocumentResponse';


export interface ApiResponseCreateDocumentResponse { 
    result?: CreateDocumentResponse;
    errorCode?: string;
    message?: string;
    responseCode?: number;
}

