/**
 * contract-service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateContractRequest { 
    customerId: string;
    dateOfBirth: string;
    name: string;
    nationalId: string;
    bankAccount: string;
    bankName: string;
    amount: string;
    loanCode: string;
    company?: string;
    businessRegistrationNumber?: string;
    companyAddress?: string;
    companyPhoneNumber?: string;
    representative?: string;
}

