/**
 * contract-service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyName } from './companyName';
import { SigningPosition } from './signingPosition';
import { DocumentType } from './documentType';


export interface DocumentSigningLocationEntity { 
    id?: string;
    companyName?: CompanyName;
    documentType?: DocumentType;
    page?: number;
    positionBorrower?: SigningPosition;
    positionInvestor?: SigningPosition;
    positionEpay?: SigningPosition;
}

