/**
 * contract-service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OtpType } from './otpType';


export interface SendLetterOTPRequest { 
    email: string;
    dateOfBirth: string;
    name: string;
    address: string;
    mobile: string;
    nationalId: string;
    customerId: string;
    employeeCode?: string;
    idIssuePlace: string;
    documentPath: string;
    otpType: OtpType;
    gender: string;
}

