/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomerAccountEntity { 
    createdAt?: string;
    updatedAt?: string;
    createdBy?: string;
    updateBy?: string;
    id?: string;
    mobile?: string;
    passwordHash?: string;
    userStatus?: CustomerAccountEntity.UserStatusEnum;
    unLockTime?: string;
    isDelete?: boolean;
}
export namespace CustomerAccountEntity {
    export type UserStatusEnum = 'ACTIVE' | 'LOCKED';
    export const UserStatusEnum = {
        Active: 'ACTIVE' as UserStatusEnum,
        Locked: 'LOCKED' as UserStatusEnum
    };
}


